[package]
name = "wasm-pack-test"
version = "0.1.0"
authors = ["Sven Sauleau <sven@sauleau.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.73"
grep-matcher = "0.1.5"
grep-regex = "0.1.9"
grep-searcher = "0.1.8"
regex = "1.1"
